[2022-11-21 12:41:21] request.INFO: Matched route "admin_module_configure_action". {"route":"admin_module_configure_action","route_parameters":{"_controller":"PrestaShopBundle\\Controller\\Admin\\Improve\\ModuleController::configureModuleAction","_legacy_controller":"AdminModules","module_name":"sendinblue","_route":"admin_module_configure_action"},"request_uri":"http://localhost:8080/admin633f195mw/index.php/improve/modules/manage/action/configure/sendinblue?_token=Z11rkqIepzUQbJk6LVUoOn9PJxIDKI8Ac89ryk8VLes","method":"GET"} []
[2022-11-21 12:41:21] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2022-11-21 12:41:21] security.DEBUG: User was reloaded from a user provider. {"provider":"PrestaShopBundle\\Security\\Admin\\EmployeeProvider","username":"dawid200107@wp.pl"} []
[2022-11-21 12:41:30] app.ERROR: Data from PrestaShop Addons is invalid, and cannot fallback on cache.  {"exception":"cURL error 28: Operation timed out after 5000 milliseconds with 400084 bytes received"} []
[2022-11-21 12:41:30] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2023-01-22 12:01:38] request.INFO: Matched route "metrics_api_resolver". {"route":"metrics_api_resolver","route_parameters":{"query":"getShopData","_controller":"PrestaShop\\Module\\Ps_metrics\\Controller\\Admin\\MetricsResolverController::resolve","_route":"metrics_api_resolver"},"request_uri":"https://localhost:18184/admin633f195mw/index.php/modules/metrics/api/getShopData?_token=56VLqYyUUq5QqpS-Um4W2LTAwMLApBMo7RapAI1QeHw","method":"GET"} []
[2023-01-22 12:01:38] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2023-01-22 12:01:38] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/modules/metrics/api/getShopData" is not callable. Class "PrestaShop\Module\Ps_metrics\Controller\Admin\MetricsResolverController" does not exist." at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php line 91 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/modules/metrics/api/getShopData\" is not callable. Class \"PrestaShop\\Module\\Ps_metrics\\Controller\\Admin\\MetricsResolverController\" does not exist. at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php:91)"} []
[2023-01-22 12:01:38] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
